name: ActionLint

on:
  push:
    paths:
      - .github/workflows/** 
  workflow_dispatch:

jobs:
  call-actionlint-workflow:
    uses: svekar/reusable-workflows/.github/workflows/actionlint.yaml@main # main 
